# Generated by Django 3.1.4 on 2020-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='desc_hospital',
            field=models.TextField(default='teste', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
