# Generated by Django 3.1.4 on 2020-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelaInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cabebalho', models.TextField(max_length=200)),
                ('titulo', models.TextField(max_length=200)),
                ('descricao', models.TextField(max_length=200)),
                ('box_1_titulo', models.TextField(blank=True, null=True)),
                ('box_1_descricao', models.TextField(blank=True, null=True)),
                ('box_1_foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('box_2_titulo', models.TextField(blank=True, null=True)),
                ('box_2_descricao', models.TextField(blank=True, null=True)),
                ('box_2_foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
